spring:
  application:
    name: device-service

  datasource:
    url: jdbc:mysql://devices_db:3306/devices_db
    username: devices_user
    password: devices_pass
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: rabbitmq_user
    password: rabbitmq_pass
    listener:
      simple:
        acknowledge-mode: auto
        prefetch: 1
        retry:
          enabled: true
          initial-interval: 3000
          max-attempts: 3
          multiplier: 2.0

app:
  rabbitmq:
    exchange:
      sync: sync.exchange
    queue:
      sync: sync.queue
    routing-key:
      user-sync: user.sync
      device-sync: device.sync

server:
  port: 8082